### ISSUE TITLE
Implement Database

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/professor-bloom#20]
```[tasklist]
### Tasks
- [ ] Store welcomer deafult messages
- [ ] store new user, inital welcome msg sent, and timestamp data for inital, 7day, and 30 day followups
- [ ] Store all ticket / status data as slacker is not a reliable source of truth
```

**Comment by jaspermayone** [comment]
@rayhanadev how's this doing?
